spring:
  profiles:
    default: local #??????? Spring ?? ?????????
  datasource: #????????? ?????????? ? ???? ?? ?????????
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL} #????? ????????????? ????? ?????????? ?????????
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false #?? ????????? ???????? ????? SQL
    hibernate.ddl-auto: validate #Hibernate ????? ?????? ????????? ?????
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true #??????? ?? ?????????
    contexts: schema, data #????????? ?? ?????????
    change-log: classpath:db.changelog.xml #???? ? ??????? ????????? Liquibase
    liquibaseSchema: liquibase #????????? ????? ???? ??? liquibase
    default-schema: dict #????? ???? ??? ??????????
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
---
spring:
  config.activate.on-profile: test #?????????? ???????? ???????? ??? ????????? ???????
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect #?????????? H2 ??? ??????
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:domain1-db;MODE=PostgreSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS LIQUIBASE\;CREATE SCHEMA IF NOT EXISTS DICT\;SET SCHEMA DICT;
    username: sa
    password:
  liquibase:
    user: sa
    password:
    contexts: schema
